TennisClubWebsite/TennisClubWebsite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from views import *

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                           # url(r'^$', 'TennisClubSite.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^ladder/', include('ladder.urls',namespace="ladder")),
                       url(r'^polls/', include('polls.urls', namespace="polls")),
                       url(r'^admin', include(admin.site.urls)),
                       url(r'^base', base),
                       url(r'^index$',index),
                       url(r'^about$',about),
                       url(r'^news$',news),
                       url(r'^roster$',roster),
                       url(r'^media$',media),
                       url(r'^faq$',faq),
                       url(r'^contact$',contact),
                       url(r'', homepage),
                       )

TennisClubWebsite/ladder/urls.py
from django.conf.urls import patterns, url
from ladder import views

urlpatterns = patterns('',
                       url(r'^roster$', views.roster, name='roster'),
                       url(r'^record$', views.record, name='record'),
                       url(r'^recorded$', views.recorded, name='recorded'),
                       url(r'^history$', views.history, name='history'),
                       url(r'^singles$',views.rankings_singles,name='rankings_singles'),
                       url(r'^doubles$',views.rankings_doubles,name='rankings_doubles'),
)

TennisClubWebsite/polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
                      url(r'', views.index),
    )

TennisClubWebsite/ladder/models.py
from django.db import models
from django.contrib.auth.models import User
from ast import literal_eval
    

class MatchStats(models.Model):
    """
    Stores match statistics that are displayed on ladder webpage. Each PlayerProfile as well as each Team has a reference to one such objects
    """
    basescore          = models.IntegerField(default=0)
    score              = models.IntegerField(default=0)
    
    numplayed          = models.IntegerField(default=0)
    numwon             = models.IntegerField(default=0)
    percentwon         = models.IntegerField(default=0)
         

class PlayerProfile(models.Model):
    user      = models.OneToOneField(User)    
    MALE      = 'M'
    FEMALE    = 'W'
    GENDER_CHOICES = ((MALE,'Male'),(FEMALE,'Female'))
    gender = models.CharField(max_length=1,choices=GENDER_CHOICES,default=MALE) 
    #matches   = models.ManyToManyField(Match,blank='true')
    matchstats = models.OneToOneField(MatchStats)
    
    def __unicode__(self):
        return self.user.username
    #Additional User Attributes

    def score_from_matchlist(self,matchlist):
        """
        Given list of matches, calculate total score.
        Score is calculated as:
        +1 for every match played
        An additional +2 for every match won
        """
        score = self.basescore + len(matchlist)
        for match in matchlist:
            if match.isWinner(self):
                score += 1
        return score
                        
    def score_all(self):
        return self.score_from_matchlist(self.matches.all())

    def score_singles(self):
        return self.score_from_matchlist(self.matches.get(matchtype__exact="singles"))
    
    
class DoublesTeamProfile(models.Model):
    """
    Always enter the team such that player1 is alphabetically before player 2
    """
    player1  = models.ForeignKey(PlayerProfile, related_name='player1')
    player2  = models.ForeignKey(PlayerProfile, related_name='player2')
    MALE     = 'M'
    FEMALE   = 'W'
    MIXED    = 'X'
    GENDER_CHOICES = ((MALE,'Male'),(FEMALE,'Female'),(MIXED,'Mixed'))
    gender   = models.CharField(max_length=1,choices=GENDER_CHOICES,default=MALE)
    matchstats = models.OneToOneField(MatchStats)
                        
class Match(models.Model):    
    matchtype   = models.CharField(max_length=200)
    matchdate   = models.DateField()
    
    winner_setscore   = models.IntegerField(default=0)
    loser_setscore   = models.IntegerField(default=0)     
    #winner_id1        = models.CharField(max_length=200)
    #winner_id2        = models.CharField(max_length=200)
    #loser_id1        = models.CharField(max_length=200)
    #loser_id2        = models.CharField(max_length=200)
    winner1           = models.ForeignKey(PlayerProfile,related_name='winner1')
    winner2           = models.ForeignKey(PlayerProfile,related_name='winner2',null=True)
    loser1            = models.ForeignKey(PlayerProfile,related_name='loser1')
    loser2            = models.ForeignKey(PlayerProfile,related_name='loser2',null=True)
    class Meta:
        ordering = ('-matchdate',)
    

TennisClubWebsite/ladder/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect, HttpResponse
from ladder.models import PlayerProfile,Match,DoublesTeamProfile,MatchStats
from django.template import RequestContext, loader
from ladder.recordform import RecordForm
from django.core.exceptions import ValidationError
import rankingcalculator

def roster(request):
    template = loader.get_template('ladder/roster.html')
    context = RequestContext(request)
    return HttpResponse(template.render(context))

def record(request,err=''):
    playerlist = PlayerProfile.objects.all()
    template = loader.get_template('ladder/record.html')
    context = RequestContext(request,{
            'playerlist':playerlist,
            'error':err,
            })
    return HttpResponse(template.render(context))

    #return render(request,'ladder/record.html')


def history(request,msg=''):
    matchlist = Match.objects.all()
    template = loader.get_template('ladder/history.html')
    context = RequestContext(request,{
            'matchlist':matchlist,
            'msg':msg,
            })
    return HttpResponse(template.render(context))


def recorded(request):
    # TODO: Proper form validation. Currently very hacky
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    
    if user is None:
        return record(request,'*** ERROR: User login information is not valid')

    form = RecordForm(request.POST)
    if not form.is_valid():
        return record(request,'*** ERROR: Please check if Match Type, Date and scores are valid')
    matchtype = request.POST['matchtype']
    matchdate = request.POST['matchdate']
    team1_id1 = request.POST['team1id1']
    team1_player1 = PlayerProfile.objects.get(user__username__exact = team1_id1)
    team2_id1 = request.POST['team2id1']
    team2_player1 = PlayerProfile.objects.get(user__username__exact = team2_id1)
    team1_setscore = request.POST['team1_setscore']
    team2_setscore = request.POST['team2_setscore']
    team1_id2 = request.POST['team1id2']
    team2_id2 = request.POST['team2id2']
    
    #if (team1_setscore !=6) and (team2_setscore !=6):
    #    print team1_setscore, team2_setscore, (team1_setscore!=6)
#return record(request,'*** ERROR! The winner has to have 6 games.')

    if (team1_id1 == team2_id1):
        return record(request,'*** ERROR: Same player on both sides of the net!')

    if team1_setscore > team2_setscore:
        winner1 = team1_player1
        winner_setscore = team1_setscore
        loser1 = team2_player1
        loser_setscore = team2_setscore
    else:
        winner1 = team2_player1
        winner_setscore = team2_setscore
        loser1 = team1_player1
        loser_setscore = team1_setscore

    # Add new match to the list of matches
    if matchtype=='singles':            
        if team1_id2 or team2_id2:
            return record(request,'*** ERROR: Two team members entered for a singles match.')
        if winner1.gender != loser1.gender:
            return record(request,'*** ERROR: Mixed gender singles matches are not recorded in the ladder')

        match = Match(matchtype=matchtype,matchdate=matchdate,
                      winner1 = winner1, loser1 = loser1, 
                      winner_setscore=winner_setscore,loser_setscore=loser_setscore)
        match.save()
        rankingcalculator.seven_point_system()
    else:
        if (not team1_id2) or (not team2_id2):
            return record(request,'*** ERROR: Player 2 required for doubles')
        
        if len(set([team1_id1,team1_id2,team2_id1,team2_id2])) < 4:
            return record(request,'*** ERROR: All 4 players must be unique')
            
        team1_player2 = PlayerProfile.objects.get(user__username__exact = team1_id2)
        team2_player2 = PlayerProfile.objects.get(user__username__exact = team2_id2)

        # Sort alphabetically
        if team1_id2 < team1_id1:
            temp = team1_player1
            team1_player1 = team1_player2
            team1_player2 = temp
        if team2_id2 < team2_id1:
            temp = team2_player1
            team2_player1 = team2_player2
            team2_player2 = temp
        
        # if team1 is new, make a profile for them    
        doublesteamprofile1 = DoublesTeamProfile.objects.filter(player1 = team1_player1, 
                                                             player2 = team1_player2)
        if not doublesteamprofile1:
            if team1_player1.gender == 'M' and team1_player2.gender == 'M':
                gender = 'M'
            elif team1_player1.gender == 'W' and team1_player2.gender == 'W':
                gender = 'W'
            else:
                gender = 'X'
            matchstats1 = MatchStats()
            matchstats1.save()
          
            doublesteamprofile1 = DoublesTeamProfile(player1=team1_player1,
                                                     player2=team1_player2,
                                                     gender=gender,matchstats=matchstats1)
            doublesteamprofile1.save()

        else:
            doublesteamprofile1 = DoublesTeamProfile.objects.get(player1 = team1_player1, 
                                                                 player2 = team1_player2)

        # if team2 is new, make a profile for them    
        doublesteamprofile2 = DoublesTeamProfile.objects.filter(player1 = team2_player1, 
                                                             player2 = team2_player2)
        if not doublesteamprofile2:
            if team2_player1.gender == 'M' and team2_player2.gender == 'M':
                gender = 'M'
            elif team2_player1.gender == 'W' and team2_player2.gender == 'W':
                gender = 'W'
            else:
                gender = 'X'
            matchstats2 = MatchStats()
            matchstats2.save()
            doublesteamprofile2 = DoublesTeamProfile(player1=team2_player1,
                                                     player2=team2_player2,
                                                     gender=gender,matchstats=matchstats2)  
            doublesteamprofile2.save()
        else:
            doublesteamprofile2 = DoublesTeamProfile.objects.get(player1 = team2_player1, 
                                                                    player2 = team2_player2)

        # Create match object for this match
        if team1_setscore > team2_setscore:
            winner1 = team1_player1
            winner2 = team1_player2
            loser1  = team2_player1
            loser2  = team2_player2
        else:
            winner1 = team2_player1
            winner2 = team2_player2
            loser1  = team1_player1
            loser2  = team1_player2
        match = Match(matchtype=matchtype,matchdate=request.POST['matchdate'],
                      winner1 = winner1, winner2 = winner2, loser1 = loser1, loser2 = loser2,
                      winner_setscore=winner_setscore,loser_setscore=loser_setscore)        
        match.save()
        rankingcalculator.update_matchstats_doubles_all()

    return redirect('/ladder/history',request,'Match successfully recorded!')
    
def rankings_singles(request):
    # Update player scores
    playerlist_men = PlayerProfile.objects.filter(gender='M').order_by('-matchstats__score','-matchstats__percentwon','-matchstats__numplayed')
    playerlist_women = PlayerProfile.objects.filter(gender='W').order_by('-matchstats__score','-matchstats__percentwon','-matchstats__numplayed')
    template = loader.get_template('ladder/singles.html')
    context = RequestContext(request,{
            'playerlist_men':playerlist_men,
            'playerlist_women':playerlist_women,
            })
    return HttpResponse(template.render(context))
        

def rankings_doubles(request):
    teamlist_men = DoublesTeamProfile.objects.filter(gender='M').order_by('-matchstats__percentwon','-matchstats__numplayed')
    teamlist_women = DoublesTeamProfile.objects.filter(gender='W').order_by('-matchstats__percentwon','-matchstats__numplayed')
    teamlist_mixed = DoublesTeamProfile.objects.filter(gender='X').order_by('-matchstats__percentwon','-matchstats__numplayed')
    template = loader.get_template('ladder/doubles.html')
    context = RequestContext(request,{
            'teamlist_men':teamlist_men,
            'teamlist_women':teamlist_women,
            'teamlist_mixed':teamlist_mixed,
            })
    return HttpResponse(template.render(context))

TennisClubWebsite/ladder/templates/ladder/base_ladder.html
{% extends 'base.html' %}


{% load staticfiles %}
{%block menu_roster %}<li><a href="/ladder/singles" class="active">Roster</a></li>{% endblock%}
{% block title %} CMU Tennis Club: Ladder {% endblock %}

{% block content_block %}

<br><br><br><br>
<div class="navbar navbar-static-top clearfix" role="navigation">
 <div class="navbar-header clearfix"> 
      <ul class="nav navbar-nav">
	{%block ladder_menu_roster %}<li><a href="/ladder/roster">Team Roster</a></li>{% endblock %}
	{%block ladder_menu_singles %}<li><a href="/ladder/singles">Singles Ladder</a></li>{% endblock %}
	{%block ladder_menu_doubles %}<li><a href="/ladder/doubles">Doubles Ladder</a></li>{% endblock %}
	{%block ladder_menu_history %}<li><a href="/ladder/history">Ladder History</a></li>{% endblock%}
	{%block ladder_menu_record %}<li><a href="/ladder/record">Record Match</a></li>{% endblock%}	
      </ul>
    
  </div>    
</div>
<!--<h1> {% block ladder_title %} Ladder {% endblock %} </h1>-->
{% block ladder_content_block %}
{% endblock %}
</div>
{% endblock %}

TennisClubWebsite/ladder/templates/ladder/doubles.html
{% extends 'ladder/base_ladder.html' %}
{% load staticfiles %}

{%block ladder_menu_doubles %}<li><a href="/ladder/doubles" class="active">Doubles Ladder</a></li>{% endblock%}
{%block ladder_title %} Doubles Rankings {% endblock %}
{%block ladder_content_block %}    

<div class="container clearfix mb-20">
  <p>Rankings and stats are updated once every 24 hours.</p>
  <div class="row">
    <div class="c4">
      <h2><span> Men </span></h2>
      {% if teamlist_men %}
      <table cellspacing="10">
	<tr>
	  <td><b>Rank</b></td> <td><b>Andrew ID</b></td> <td><b>Played</b></td> <td><b>Won</b></td> <td><b>Win%</b></td>
	</tr>
	{% for team in teamlist_men %}
	<tr>
	  <td>{{forloop.counter}})</td><td>{{team.player1.user.first_name}}/{{team.player2.user.first_name}}</td>
	  <td>{{team.matchstats.numplayed}}</td><td>{{team.matchstats.numwon}}</td>
	  <td>{{team.matchstats.percentwon}}</td>
	</tr>
	{% endfor %}
	{% else %}
	<p>No men's matches have been played </p>
	{% endif %}
      </table>
    </div>
    <div class="c4">
      <h2><span> Women </span></h2>
      {% if teamlist_women %}
      <table cellspacing="10">
	<tr>
	  <td><b>Rank</b></td> <td><b>Andrew ID</b></td> <td><b>Played</b></td> <td><b>Won</b></td> <td><b>Win%</b></td>
	</tr>
	{% for team in teamlist_women %}
	<tr>
	  <td>{{forloop.counter}})</td><td>{{team.player1.user.first_name}}/{{team.player2.user.first_name}}</td>
	  <td>{{team.matchstats.numplayed}}</td><td>{{team.matchstats.numwon}}</td>
	  <td>{{team.matchstats.percentwon}}</td>
	</tr>
	{% endfor %}
     	{% else %}
	<p>No women's matches have been played </p>
	{% endif %}
      </table>
    </div>
    <div class="c4">
      <h2><span> Mixed </span></h2>
      {% if teamlist_mixed %}
      <table cellspacing="10">
	<tr>
	  <td><b>Rank</b></td> <td><b>Andrew ID</b></td> <td><b>Played</b></td> <td><b>Won</b></td> <td><b>Win%</b></td>
	</tr>
	{% for team in teamlist_mixed %}
	<tr>
	  <td>{{forloop.counter}})</td><td>{{team.player1.user.first_name}}/{{team.player2.user.first_name}}</td>
	  <td>{{team.matchstats.numplayed}}</td><td>{{team.matchstats.numwon}}</td>
	  <td>{{team.matchstats.percentwon}}</td>
	</tr>
	{% endfor %}
     	{% else %}
	<p>No mixed matches have been played </p>
	{% endif %}
      </table>
    </div>
  </div>
</div>
{% endblock %}

TennisClubWebsite/ladder/templates/ladder/history.html
{% extends 'ladder/base_ladder.html' %}
{% load staticfiles %}

{%block ladder_menu_history %}<li><a href="/ladder/history" class="active">Ladder History</a></li>{% endblock%}
{%block ladder_title %} Match History {% endblock %}
{%block ladder_content_block %}    
<div class="container clearfix mb-20">
<h2>{{msg}}</h2>
List of all matches played so far.
{% if matchlist %}
    <table cellspacing="30" align="center">
      <tr> <td><b>Date Played</b></td> <td><b>Format</b></td>  <td><b>Player/Team 1</b></td>  <td><b>Score</b></td> <td><b>Player/Team 2</b></td>  
      </tr>
      {% for match in matchlist %}
      <tr>
	<td>{{match.matchdate}}</td> <td>{{match.matchtype}}</td> <td>{{match.winner1.user.first_name}} {{match.winner2.user.first_name}}</td><td>{{match.winner_setscore}}-{{match.loser_setscore}}</td> <td>{{match.loser1.user.first_name}} {{match.loser2.user.first_name}}</td> 
      </tr>
      {% endfor %}
    </table>
</ul>
{% else %}
<p>No matches have been played. </p>
{%endif %}
<br>
</div>
{% endblock %}

TennisClubWebsite/ladder/templates/ladder/record.html
{% extends 'ladder/base_ladder.html' %}
{% load staticfiles %}

{%block ladder_menu_record %}<li><a href="/ladder/record" class="active">Record Match</a></li>{% endblock%}
{%block ladder_title %} Record Match {% endblock %}
{%block ladder_content_block %}    
<div class="container clearfix mb-20">
  <h3><span> {{error}}</span> </h3>
  <b> Rules: </b> <br>
  Only matches played during club practice will count towards the ladder.<br>
  Ladder matches are all 6 game no-ad sets. A regular tie-break (first to 7, win by 2) is played at 5-5.  
  <form action="{% url 'ladder:recorded' %}" method="post">
    {% csrf_token %}
    {{form}}
    <h2> <span> Login information </span></h2>
    <table>
      <tr>
	<td align="right"> Username : <input type=text name = "username"></td>
      </tr>
      <tr>
	<td align="right"> Password  : <input type=password name = "password"><br></td>
      </tr>
    </table>
    <h2> <span> Match Type </span></h2>
    <input type="radio" name="matchtype"  value="singles"> Singles <br>
    <input type="radio" name="matchtype"  value="doubles"> Doubles <br>
    
    <h2><span> Date Played</span></h2>
    <input type="date"  name ="matchdate"><br>
    
    <h2><span> Team 1 </span></h2> 
    Player 1
    <select name="team1id1">
      {% for player in playerlist %}
      <option value={{player.user.username}}>{{player.user.first_name}}</option>
      {% endfor %}
    </select>
    Player 2
    <select name="team1id2">
      <option value="">None</option>
      {% for player in playerlist %}
      <option value={{player.user.username}}>{{player.user.first_name}}</option>
      {% endfor %}
    </select>
    Set Score <input type=number name = "team1_setscore"> <br>
    <h2><span> Team 2 </span></h2>
    Player 1 
    <select name="team2id1">
      {% for player in playerlist %}
      <option value={{player.user.username}}>{{player.user.first_name}}</option>
      {% endfor %}
    </select>
    Player 2
    <select name="team2id2">
      <option value=''>None</option>
      {% for player in playerlist %}
      <option value={{player.user.username}}>{{player.user.first_name}}</option>
      {% endfor %}
    </select>
    Set Score <input type=number name = "team2_setscore"><br>
    <br>
    <input type="Submit" value="Submit"/>
    <br><br>
  </form>
</div>
{% endblock %}

TennisClubWebsite/ladder/templates/ladder/roster.html
{% extends 'ladder/base_ladder.html' %}
{% load staticfiles %}

{%block ladder_menu_roster %}<li><a href="/ladder/roster" class="active">Team Roster</a></li>{% endblock%}
{%block ladder_content_block %}    
<!--Singles Points are calculated using a 7-point version of the scoring system described <a href="http://www.tennisengine.com/info/ranksys_9.asp"> here </a>.-->

<div class="container clearfix mt-100 mb-20">
      <div class="c12 row">
        <h2><span>Officers</span></h2>
        <div class = "c5">
          <p class="name"> Captain (Men) </p>
          <p class="position"> Vikram Shanker <br> (Andrew id: vshanker) </p>
          <br>
          <p class="name"> Vice-Captain (Men) </p>
          <p class="position"> Abhinand Sukumar  <br> (Andrew id: abhinans) </p>
        </div>
	<div class = "c5">
          <p class="name"> Captain (Women) </p>
          <p class="position"> Rebecca Kern <br> (Andrew id: rkern) </p>
          <br>
          <p class="name"> Vice-Captain (Women) </p>
          <p class="position"> Jennifer Jin <br> (Andrew id: jj1) </p>
	  </div>
      </div>
 </div><!-- /.container -->

<div class="container clearfix mt-50 mb-20">
  <div class="c12 row">
    <h2><span>Current Team Members</span></h2>
    <div class = "c5">
      <h3> Men </h3>
      <br>
      <ul>
	<dt> Benjamin Chang </dt>
        <dt> Karthik Lakshmanan </dt>
	<dt> Giovanni Leoni </dt>
	<dt> Nicholas Mu </dt>
	<dt> Julien Naegeli </dt>
	<dt> Chris Park </dt>
	<dt> Vikram Shanker </dt>
	<dt> Abhinand Sukumar </dt>
	<dt> Shiv Wadwani </dt>
	<dt> David Yu </dt>
      </ul>
    </div>
    <div class = "c5">
      <h3> Women </h3>
      <br>
      <dt> Allie Del Giorno </dt>
      <dt> Jennifer Jin </dt>
      <dt> Evaline Ju </dt>
      <dt> Rebecca Kern </dt>
      <dt> Tiffany Zhu </dt>
    </div>
  </div>
</div>
<br>
{% endblock %}

TennisClubWebsite/ladder/templates/ladder/singles.html
{% extends 'ladder/base_ladder.html' %}
{% load staticfiles %}

{%block ladder_menu_singles %}<li><a href="/ladder/singles" class="active">Singles Ladder</a></li>{% endblock%}
{%block ladder_content_block %}    
<div class="container clearfix mb-20">
 <p>Singles Points are calculated using a 7-point version of the scoring system described <a href="http://www.tennisengine.com/info/ranksys_9.asp"> here </a>. </p>
  <p>Rankings and stats are updated once every 24 hours.</p>
  <div class="row">
    <div class="c6">
      <h2><span> Men </span></h2>
      {% if playerlist_men %}
      <table cellspacing="20">
	<tr>
	  <td><b>Rank</b></td> <td><b>Name</b></td> <td><b>Points</b></td> <td><b>Played</b></td> <td><b>Won</b></td> <td><b>Win%</b></td>
	</tr>
	{% for player in playerlist_men %}
	<tr>
	  <td>{{forloop.counter}})</td><td>{{player.user.first_name}}</td> <td>{{player.matchstats.score}} </td>
	  <td>{{player.matchstats.numplayed}}</td><td>{{player.matchstats.numwon}}</td>
	  <td>{{player.matchstats.percentwon}}</td>
	</tr>
	{% endfor %}
	{% else %}
	<p>No men's matches have been played </p>
	{% endif %}
      </table>
    </div>
    <div class="c6">
      <h2><span> Women </span></h2>
      {% if playerlist_women %}
      <table cellspacing="20">
	<td><b>Rank</b></td> <td><b>Name</b></td> <td><b>Points</b></td> <td><b>Played</b></td> <td><b>Won</b></td> <td><b>Win%</b></td>
	{% for player in playerlist_women %}
	<tr>
	  <td>{{forloop.counter}})</td><td>{{player.user.first_name}}</td> <td>{{player.matchstats.score}} </td>
	  <td>{{player.matchstats.numplayed}}</td><td>{{player.matchstats.numwon}}</td>
	  <td>{{player.matchstats.percentwon}}</td>
	</tr>
	{% endfor %}
	{% else %}
	<p>No women's matches have been played </p>
	{% endif %}
      </table>
    </div>
  </div>
</div>
{% endblock %}